### ISSUE TITLE
Launch error on OS X 10.11.3

### ISSUE THREAD

**Issue by ryentzer** [jlord/git-it-electron#97]
I get this error upon launch:

```
Uncaught Exception:
Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/Git-it.app/Contents/Resources/app/main.js:4:11)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/Applications/Git-it.app/Contents/Resources/atom.asar/browser/lib/init.js:108:10)
```

**Comment by jlord** [comment]
Eek I think I must have messed up the last release :grin: Will maybe have to do something funky to fix it since I've changed master. But I'm on it :+1:

**Comment by jlord** [comment]
I've made the fix and it launches on my computer, but if you could, give the OS X version on this release a go and let me know if it doesn't work out: https://github.com/jlord/git-it-electron/releases/tag/3.1.0

**Comment by ryentzer** [comment]
This worked for me now. Thanks for creating this!
